### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by MrGallo** [Gallo-ICS2O1a/cpt-christian-p-1#1]
Lists. Google:
Python lists

Learn how to:
1. Create them
2. Append to them
3. Remove elements from them
4. Loop through them to print each element in the list

Once you are comfortable with lists...
- Then populate a list with some PVectors
- Then loop through that list to draw ellipses at the pvector location
- Each lazer will be a pvector. You loop through it to update it’s position,
- check for collisions and draw it.

**Comment by MrGallo** [comment]
How far did you get with this?

**Comment by CPatroiu** [comment]
I got stuck on it during the break, and revisited it today, I understand lists, but not how to loop through them.
